version: '3.9'

services:
  postgres:
    container_name: sem_pressa_postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    container_name: sem_pressa_app
    build: .
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=docker
    depends_on:
      - postgres

volumes:
  postgres_data:
