describe('Teste Login', () => {
  beforeEach(() => {
    // Adiciona o listener para ignorar exceções não tratadas
    Cypress.on('uncaught:exception', (err, runnable) => {
        // Retorne false para impedir que o Cypress falhe o teste
        return false
    })
})
  it('Acessando o site', () => {
    visit_site()
    cy.get('.font-semibold').should('contains.text', 'Estudante')
  })
  it('Vendo se tem o campo de usuario', () => {
    visit_site()
    cy.get('.font-semibold').should('contains.text', 'Estudante')
    cy.get(':nth-child(1) > .font-medium').should('contains.text', 'Usuário')
  })
  it('Vendo se tem o campo de senha', () => {
    visit_site()
    cy.get('.font-semibold').should('contains.text', 'Estudante')
    cy.get('.space-y-4 > :nth-child(2) > .font-medium').should('contains.text', 'Senha')
  })
  it('Acessando a página de login de Estudante', () => {
    visit_site()
    cy.get('#radix-\\:rb\\:-trigger-student').should('be.visible').click()
    cy.get('.font-semibold').should('contains.text', 'Estudante')
  })
  it('Logando como Estudante', () => {
    visit_site()
    cy.get('#radix-\\:rb\\:-trigger-student').should('be.visible').click()
    cy.get('.font-semibold').should('contains.text', 'Estudante')
    cy.get('#admin-username').type('student@inatel.br')
    cy.get('#admin-password').type('127450')
    cy.get('.flex.items-center > .inline-flex').click()
    cy.get(':nth-child(1) > .mb-4 > .text-2xl').should('contains.text', 'Project Data')
  })
  it('Logando como Estudante e dando logout', () => {
    visit_site()
    cy.get('#radix-\\:rb\\:-trigger-student').should('be.visible').click()
    cy.get('.font-semibold').should('contains.text', 'Estudante')
    cy.get('#admin-username').type('student@inatel.br')
    cy.get('#admin-password').type('127450')
    cy.get('.flex.items-center > .inline-flex').click()
    cy.get(':nth-child(1) > .mb-4 > .text-2xl').should('contains.text', 'Project Data')
    cy.get('#radix-\\:r8\\: button').click()
    cy.contains('Sair').should('be.visible').click()
    cy.reload()
    cy.get('.text-center > .text-sm').should('contains.text', 'Entre com suas student credenciais abaixo.')
    
  })
  it('Logando como Estudante com usuário errado', () => {
    visit_site()
    cy.get('#radix-\\:rb\\:-trigger-student').should('be.visible').click()
    cy.get('.font-semibold').should('contains.text', 'Estudante')
    cy.get('#admin-username').type('student123@inatel.br')
    cy.get('#admin-password').type('12121127450')
    cy.get('.flex.items-center > .inline-flex').click()
    cy.get('.text-center > .text-sm').should('contains.text', 'Entre com suas student credenciais abaixo.')
  })
  it('Acessando a página de login de Orientador', () => {
    visit_site()
    cy.get('#radix-\\:rb\\:-trigger-advisor').should('be.visible').click()
    cy.get('.font-semibold').should('contains.text', 'Orientador')
  })
  it('Logando como Orientador', () => {
    visit_site()
    cy.get('#radix-\\:rb\\:-trigger-advisor').should('be.visible').click()
    cy.get('.font-semibold').should('contains.text', 'Orientador')
    cy.get('#admin-username').type('advivi@inatel.br')
    cy.get('#admin-password').type('127450')
    cy.get('.flex.items-center > .inline-flex').click()
    cy.get('.grid > :nth-child(1) > .flex > .text-2xl').should('contains.text', 'Informações da FETIN')
  })
  it('Logando como Orientador e dando logout', () => {
    visit_site()
    cy.get('#radix-\\:rb\\:-trigger-advisor').should('be.visible').click()
    cy.get('.font-semibold').should('contains.text', 'Orientador')
    cy.get('#admin-username').type('advivi@inatel.br')
    cy.get('#admin-password').type('127450')
    cy.get('.flex.items-center > .inline-flex').click()
    cy.get('.grid > :nth-child(1) > .flex > .text-2xl').should('contains.text', 'Informações da FETIN')
    cy.get('#radix-\\:r8\\: button').click()
    cy.contains('Sair').should('be.visible').click()
    cy.reload()
    cy.get('.text-center > .text-sm').should('contains.text', 'Entre com suas student credenciais abaixo.')
  })
  it('Logando como Orientador com usuário errado', () => {
    visit_site()
    cy.get('#radix-\\:rb\\:-trigger-advisor').should('be.visible').click()
    cy.get('.font-semibold').should('contains.text', 'Orientador')
    cy.get('#admin-username').type('123advivi@inatel.br')
    cy.get('#admin-password').type('123127450')
    cy.get('.flex.items-center > .inline-flex').click()
    cy.wait(1000)
    cy.get('.text-center > .text-sm').should('contains.text', 'Entre com suas advisor credenciais abaixo.')
  })
  it('Acessando a página de login de ADM', () => {
    visit_site()
    cy.get('#radix-\\:rb\\:-trigger-admin').should('be.visible').click()
    cy.get('.font-semibold').should('contains.text', 'Administrador')
  })
  it('Logando como ADM', () => {
    visit_site()
    cy.get('#radix-\\:rb\\:-trigger-admin').should('be.visible').click()
    cy.get('.font-semibold').should('contains.text', 'Administrador')
    cy.get('#admin-username').type('admin12356789@inatel.br')
    cy.get('#admin-password').type('123456789')
    cy.get('.flex.items-center > .inline-flex').click()
    cy.get('.text-white').should('contains.text', 'Adicionar Equipe')
    cy.get('#radix-\\:r8\\: button').click()
    cy.contains('Sair').should('be.visible').click()
  })
  it('Logando como ADM e dando logout', () => {
    visit_site()
    cy.get('#radix-\\:rb\\:-trigger-admin').should('be.visible').click()
    cy.get('.font-semibold').should('contains.text', 'Administrador')
    cy.get('#admin-username').type('admin12356789@inatel.br')
    cy.get('#admin-password').type('123456789')
    cy.get('.flex.items-center > .inline-flex').click()
    cy.get('.text-white').should('contains.text', 'Adicionar Equipe')
    cy.get('#radix-\\:r8\\: button').click()
    cy.contains('Sair').should('be.visible').click()
    cy.reload()
    cy.get('.text-center > .text-sm').should('contains.text', 'Entre com suas student credenciais abaixo.')
    
  })
  it('Logando como ADM com usuário errado', () => {
    visit_site()
    cy.get('#radix-\\:rb\\:-trigger-admin').should('be.visible').click()
    cy.get('.font-semibold').should('contains.text', 'Administrador')
    cy.get('#admin-username').type('123admin12356789@inatel.br')
    cy.get('#admin-password').type('123123456789')
    cy.get('.flex.items-center > .inline-flex').click()
    cy.wait(1000)
    cy.get('.text-center > .text-sm').should('contains.text', 'Entre com suas admin credenciais abaixo.')
  })
  it('Acessando o site e escolhendo o tema claro', () => {
    visit_site()
    cy.get('#radix-\\:r8\\: button').click()
    cy.contains('Tema').should('be.visible').click()
    cy.contains('Light').click()
    cy.wait(1000)
})
it('Acessando o site e escolhendo o tema escuro', () => {
  visit_site()
  cy.get('#radix-\\:r8\\: button').click()
  cy.contains('Tema').should('be.visible').click()
  cy.contains('Dark').click()
  cy.wait(1000)
})

})

function visit_site(){
  cy.viewport(1280,720)
  cy.visit('http://localhost:5173/')
}